DEST_MAC_N_OCTETS = 6
SRC_MAC_N_OCTETS = 6
ETHERTYPE_N_OCTETS = 2

ETHERNET_HEADER_N_OCTETS = (
    DEST_MAC_N_OCTETS + SRC_MAC_N_OCTETS + ETHERTYPE_N_OCTETS)

DEST_MAC_BITWIDTH = DEST_MAC_N_OCTETS*8
SRC_MAC_BITWIDTH = SRC_MAC_N_OCTETS*8
ETHERTYPE_BITWIDTH = ETHERTYPE_N_OCTETS*8

ETHERNET_HEADER_N_BITS = (
    DEST_MAC_BITWIDTH + SRC_MAC_BITWIDTH + ETHERTYPE_BITWIDTH)
